### ISSUE TITLE
Just thank you!

### ISSUE THREAD

**Issue by mysticaltech** [pleonova/stat-tests#1]
My issue is how cool this board is. Damn, it's the map of the mind of a decent statistician! Thank you so much for sharing this. It will help me a lot in my own personal journey in experimentation. Be well and keep up the good work! 🙏 ✨

**Comment by pleonova** [comment]
Hello Karim, I am very happy to hear that you found the map helpful! If you have any questions or suggestions, I am all ears.

**Comment by mysticaltech** [comment]
Perfect, glad to hear that, I won't hesitate!
